# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
      statuses: write
      packages: read

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 10
    - name: install node
      run: |
       sudo apt update
       curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - &&\
       sudo apt-get install -y nodejs
       sudo apt-get install -y build-essential    
    - name: Build with Maven
      continue-on-error: true
      run: mvn clean verify -Dtestng.dtd.http=true
    - uses: deblockt/cucumber-report-annotations-action@v1.11
      with:
        access-token: ${{ secrets.GITHUB_TOKEN }}
        path: "**/cucumber.json"
        check-status-on-error: success
        check-status-on-undefined: success
        check-status-on-pending: success
        annotation-status-on-error: success
        show-number-of-error-on-check-title: true
    - name: Deploy report page to GitHub Page
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target
